services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: raspbocapi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:3
    build:
      context: packages/opensearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q cluster_name"]
      interval: 10s
      timeout: 5s
      retries: 5

  oni-ui:
    image: ghcr.io/crate-works/oni:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/oni-ui.json:/configuration.json
      - ./docker/logo.png:/usr/share/nginx/html/logo.png

volumes:
  mysql_data:
  opensearch_data:
