# Open WiFi AP for RaspboCrate
interface=wlan0
driver=nl80211
ssid=raspbocrate-XXXX
hw_mode=g
channel=7
wmm_enabled=0
ieee80211n=1
country_code=AU
auth_algs=1
logger_syslog=-1
logger_syslog_level=2
macaddr_acl=0
ignore_broadcast_ssid=0
