# Open WiFi AP for RaspboCrate
interface=wlan0
driver=nl80211
country_code=AU

hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
ht_capab=[HT40][SHORT-GI-20][DSSS_CCK-40]
macaddr_acl=0
ignore_broadcast_ssid=0
# Make MFP optional
ieee80211w=1

auth_algs=1
ssid=raspbocrate-XXXX

logger_syslog=-1
logger_syslog_level=2
